language: java
jdk:
  - openjdk11

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

deploy:
  provider: heroku
  api-key:
    secure: 1f391bea-693a-4b20-980a-2d0a9b1905aa
  app: hoaxify
  skip_cleanup: true

edge: true