spring:
  profiles:
    active: dev
server:
  port: 8000

---
spring:
  profiles: production
hoaxify:
  upload-path: storage-production
---
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 100
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hoaxify?useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  profiles: dev

hoaxify:
  upload-path: storage-dev



