spring:
  profiles:
    active: dev
hoaxify:
  upload-path: storage-dev
  file-cleanup-time: 1000000


---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://localhost:5432/hoax
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          validation:
            mode: none
  servlet:
    multipart:
      max-file-size: 10MB
hoaxify:
  upload-path: storage-production
server:
  port: 8000
---
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 100
    show-sql: true
  datasource:
    url: jdbc:h2:./devdb
  profiles: dev
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8000


